package sdl

type WindowPointerProperty int

const (
	WindowPointerPropertyWin32HWND WindowPointerProperty = iota
	WindowPointerPropertyWin32HDC
	WindowPointerPropertyWin32Instance
	WindowPointerPropertyWaylandDisplay
	WindowPointerPropertyWaylandSurface
	WindowPointerPropertyX11Display
)
