/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/inject_overlay_notifier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Overlay Notifier
         * @description Injects overlay notifier into Steams shared context
         */
        post: operations["inject_overlay_notifier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/input_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Input Info
         * @description Returns information about the controllers detected
         */
        get: operations["get_input_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overlay_state_changed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * On overlay change
         * @description Callback for when the steam overlay is opened or closed.
         */
        post: operations["on_overlay_state_changed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/steam_cef_reachable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Steam CEF Remote Debugging Reachability
         * @description Returns whether the CEF remote debugging interface of Steam is reachable.
         */
        get: operations["steam_cef_reachable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/steam_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Steam Status
         * @description Returns information about Steam, the SISR marker shortcut, and the CEF remote debugging (of Steam)
         */
        get: operations["steam_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ControllerInfoResponse: {
            devices: {
                [key: string]: components["schemas"]["DeviceInfo"];
            };
            keyboard_mouse_emulation: boolean;
            steam_overlay_open: boolean;
            viiper: components["schemas"]["ViiperInfo"];
        };
        DeviceInfo: {
            /** Format: int64 */
            corresponding_device_id?: number | null;
            has_viiper_device: boolean;
            /** Format: int32 */
            sdl_device_count: number;
            sdl_devices: components["schemas"]["SDLDeviceInfo"][];
            /** Format: int64 */
            steam_handle: number;
            viiper_type?: string | null;
        };
        OverlayStateChangePayload: {
            open: boolean;
        };
        /** @description RFC 9457 / RFC 7807 problem details */
        ProblemDetails: unknown & {
            /**
             * @description An optional human-readable description of this problem.
             *
             *     See [https://www.rfc-editor.org/rfc/rfc9457.html#name-detail]() for more information.
             */
            detail?: string | null;
            /**
             * Format: uri
             * @description An optional uri identifying the specific instance of this problem.
             *
             *     See [https://www.rfc-editor.org/rfc/rfc9457.html#name-instance]() for more information.
             */
            instance?: string;
            /**
             * Format: int32
             * @description An optional status code for this problem.
             *
             *     See [https://www.rfc-editor.org/rfc/rfc9457.html#name-status]() for more information.
             */
            status?: number;
            /**
             * @description An optional human-readable title for this problem.
             *
             *     See [https://www.rfc-editor.org/rfc/rfc9457.html#name-title]() for more information.
             */
            title?: string | null;
            /**
             * Format: uri
             * @description An optional uri describing the problem type.
             *
             *     See [https://www.rfc-editor.org/rfc/rfc9457.html#name-type]() for more information.
             */
            type?: string;
        };
        RemoteCefReachable: {
            reachable: boolean;
        };
        RemoteDebugStatus: {
            enabled: boolean;
            /** Format: int32 */
            port: number;
        };
        SDLDeviceInfo: {
            gamepad_infos: {
                [key: string]: components["schemas"]["SdlValue"];
            };
            joystick_infos: {
                [key: string]: components["schemas"]["SdlValue"];
            };
        };
        SdlValue: string | (string | null) | number | (number | null) | (number | null) | boolean | Record<string, never>;
        SteamStatus: {
            launched_via_steam: boolean;
            /** Format: int32 */
            marker_app_id?: number | null;
            marker_shortcut_present: boolean;
            path?: string | null;
            remote_debug: components["schemas"]["RemoteDebugStatus"];
            running: boolean;
            /** Format: int64 */
            steam_game_id: number;
        };
        ViiperInfo: {
            address?: string | null;
            address_is_loopback: boolean;
            available: boolean;
            bus_ids: number[];
            version?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    inject_overlay_notifier: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Steam CEF Debugging not reachable */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_input_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControllerInfoResponse"];
                };
            };
        };
    };
    on_overlay_state_changed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayStateChangePayload"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    steam_cef_reachable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoteCefReachable"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    steam_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SteamStatus"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
